server.port=2209
spring.application.name=plaza-crm
spring.datasource.url=jdbc:postgresql://localhost:5432/plaza-crm
spring.datasource.username=postgres
spring.datasource.password=iamroot
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.data.web.pageable.default-page-size=10
spring.data.web.pageable.max-page-size=50

jwt.secret=qnX9m8KXPjOk7oFZrBmVGQ4e6gsLgmfFfUlOEjY6WKo=
jwt.expiration=86400000
